# Flags for our UI
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: pizza-flags
  labels:
    app: pizza-store-service
spec:
  flagSpec:
    flags:
      v2_enabled:
        state: ENABLED
        variants:
          'true': true
          'false': false
        defaultVariant: 'true'
---
# Feature flag source custom resource, configuring flagd to source flags from FeatureFlag CRDs
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: flag-sources
  labels:
    app: pizza-store-service
spec:
  sources:
    - source: pizza-flags
      provider: kubernetes
  port: 8013
---